# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LanguageName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 'bad'), (2, 'not too bad'), (3, 'normal'), (4, 'kinda good'), (5, 'good')])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('hobby', models.CharField(blank=True, max_length=500)),
                ('contacts', models.ManyToManyField(related_name='_userprofile_contacts_+', to='language_swap.UserProfile')),
                ('practices', models.ManyToManyField(related_name='practice', to='language_swap.Language')),
                ('rating', models.ManyToManyField(through='language_swap.Rate', to='language_swap.UserProfile')),
                ('speaks', models.ManyToManyField(related_name='speak', to='language_swap.Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='ratedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated', to='language_swap.UserProfile'),
        ),
        migrations.AddField(
            model_name='rate',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raterUser', to='language_swap.UserProfile'),
        ),
    ]
