# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_swap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 'bad'), (2, 'not too bad'), (3, 'normal'), (4, 'kinda good'), (5, 'good')])),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='ratedUser',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rater',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.AddField(
            model_name='contact',
            name='contactedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted', to='language_swap.UserProfile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sourceUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='language_swap.UserProfile'),
        ),
    ]
