# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_swap', '0002_auto_20180302_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
