# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_swap', '0003_auto_20180307_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='practices',
            field=models.ManyToManyField(related_name='practices', to='language_swap.Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='speaks',
            field=models.ManyToManyField(related_name='speaks', to='language_swap.Language'),
        ),
    ]
