# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_swap', '0005_auto_20180308_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practices',
            name='language',
        ),
        migrations.RemoveField(
            model_name='practices',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='speaks',
            name='language',
        ),
        migrations.RemoveField(
            model_name='speaks',
            name='speaker',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='practices',
            field=models.ManyToManyField(related_name='practices', to='language_swap.Language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speaks',
            field=models.ManyToManyField(related_name='speaks', to='language_swap.Language'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.DeleteModel(
            name='Practices',
        ),
        migrations.DeleteModel(
            name='Speaks',
        ),
    ]
