# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_swap', '0006_auto_20180308_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], default='other', max_length=10),
        ),
    ]
