# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_swap', '0007_auto_20180309_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
